### ISSUE TITLE
Add title field in dislikes view

### ISSUE THREAD

**Issue by Rotstein1** [jesperbakhandskemager/view-youtube-dislike#1]
Hello,
I'm a hobby "plain" java developer. A few months ago I saw the app in the F-droid store and it sounded interesting, so I tried it out. Since then, I've been using the app to look how many dislikes some really bad videos had and sometimes to share them with friends.
One thing that is, in my opinion, still missing in the app is a field to show the title of the video in the dislikes view. So if you, for example, take a screenshot of the app to share it with friends, they can directly see what video is it about.
After a little bit of research I found out, that the API at [youtube.com/oembed](youtube.com/oembed) is able to return some information about the video, including the title. Using `https://youtube.com/oembed?format=json&url=[URL of the youtube video here]` the data is returned as a JSON string.
The following code snippet in normal java demonstrates the use of this API:
```
	public static String getYoutubeVideoTitle(String url)
			throws InterruptedException, URISyntaxException, IOException, ParseException {
		url = "https://youtube.com/oembed?format=json&url=" + url;

		// Request
		BodySubscriber<String> subscriber = BodySubscribers.ofString(Charset.defaultCharset());
		HttpRequest request = HttpRequest.newBuilder(new URI(url)).GET().build();
		HttpClient client = HttpClient.newHttpClient();
		String response = client.send(request, (responeInfo) -> subscriber).body();

		// JSON parsing
		JSONObject json = (JSONObject) new JSONParser().parse(new StringReader(response));
		response = (String) json.get("title");

		return response;
	}
```
Since I'm not a android developer and my computer is to old to run android studio, I can't test this on android, but it tested it  on my computer using the [json-simple](https://github.com/fangyidong/json-simple/) library and it worked as expected (Both youtube.com and youtu.be URLs).
To port it to android, my best guess is to change the request part to StringRequest, as used in [app/src/main/java/com/jesperh/showyoutubedislikes/DisplayMessageActivity.java](https://github.com/jesperbakhandskemager/view-youtube-dislike/blob/265dd880544869d917a8d510c06d2b9d7088d7a6/app/src/main/java/com/jesperh/showyoutubedislikes/DisplayMessageActivity.java), line 126 and to parse the JSON using builtin android functions.
Thanks for making this app!

**Comment by jesperbakhandskemager** [comment]
Thank you for bringing [youtube.com/oembed](https://youtube.com/oembed) to my attention, i didn't know that existed and just assumed i would have to either make a web scraper or use an api key to get the 'official' video information.

The app currently gets it's data from another json api, so i'm sure it won't be difficult to implement.

I will definitely look into this, it's great to hear people are using the app.

**Comment by jesperbakhandskemager** [comment]
This feature along with thumbnails is included in the latest version
